name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3000:3000
          - 5000:5000
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and push Docker images
      run: |
        docker-compose -f compose.yaml build
        docker-compose -f compose.yaml up -d

    - name: Run tests
      run: |
        # Retry mechanism for curl commands
        for i in {1..10}; do
          curl --fail http://localhost:3000 && break || sleep 5
        done
        for i in {1..10}; do
          curl --fail http://localhost:5000 && break || sleep 5
        done

    - name: Shutdown Docker Compose
      run: docker-compose -f compose.yaml down